trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

# 0) Install the .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'          # or '9.x' depending on your project
    performMultiLevelLookup: true

# 1) Restore NuGet packages via dotnet CLI
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: '**/*.sqlproj'

# 2) Build the SQL Project to generate the DACPAC
- task: DotNetCoreCLI@2
  displayName: 'Build SQL Project'
  inputs:
    command: 'build'
    projects: 'wh_Bronze/wh_Bronze.sqlproj'
    arguments: '--configuration $(buildConfiguration) /p:OutputPath=$(Build.ArtifactStagingDirectory)'

# 3) Publish the DACPAC as an artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish DACPAC Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'
